#!/bin/sh
config=config
helper=doashelper
[ "$2" = "--nohelper" ] && helper="doas"
if [ "$(whereis doas)" = "" ]; then
	echo "Doas is missing \n if using sudo, do \n \`alias doas=sudo\`"
	exit
fi

dwm(){
name="dwm"
version="6.3"
src="dl.suckless.org/$name/$name-$version.tar.gz"
}

dmenu(){
name="dmenu"
version="5.1"
src="dl.suckless.org/tools/$name-$version.tar.gz"
}

dwmblocks(){
name="dwmblocks"
version="master"
src="https://github.com/torrinfail/$name/archive/refs/heads/$version.tar.gz"
config=blocks
}

st(){
name="st"
version="0.8.5"
src="dl.suckless.org/$name/$name-$version.tar.gz"
}

slock(){
name="slock"
version="1.4"
src="dl.suckless.org/tools/$name-$version.tar.gz"
}

pinentrydmenu(){
name="pinentry-dmenu"
version="master"
src="https://github.com/ritze/$name/archive/refs/heads/$version.tar.gz"
}

surf(){
name="surf"
version="2.1"
src="dl.suckless.org/$name/$name-$version.tar.gz"
}

patcher(){
for i in ~/.local/src/patches/"$name"/*.diff
do
	patch -p1 -i "$i" -d /tmp/$name-$version
done
}

configurer(){
cp ~/.local/src/configs/$name/$config.h /tmp/$name-$version/$config.h
}

build(){
$1
curl -L $src -o /tmp/$name.tar.gz
tar xzf /tmp/$name.tar.gz -C /tmp
patcher
configurer
$helper make install -C /tmp/$name-$version
rm -rf /tmp/$name-$version /tmp/$name.tar.gz
}

help(){
echo "Usage:\n ./build \"program name\" or \"all\" \n --nohelper: won't call doashelper" 
exit
}

[ "$1" = "-h" ] && help 

if [ "$1" != "" ] && [ "$1" != "all" ]; then
	build "$1"
elif [ "$1" = all ]; then
	build dwm
	build st
	build dmenu
	build slock
	build pinentrydmenu
	build dwmblocks
	build surf
else 
	help
fi
